### ISSUE TITLE
Include both appAuth and userAuth.

### ISSUE THREAD

**Issue by garethpaul** [RapidSoftwareSolutions/Marketplace-Foursquare-Package#1]
I noticed that you currently provide userAuth for Foursquare, just wondered whether we might be able to add appAuth.

Specifically including client_id and client_secret in the http requests allows userless auth on a number of endpoints.

Note: Happy to work on this, but not sure what the protocol is.

**Comment by dimashirokov** [comment]
Hi garethpaul,
Thank you for your issue. 
Fixed with commit 58faacdc05fbd7d6f13794cc650ddbe92b8e12e7
